{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "digital-twin-bundle.fullname" . }}
  labels:
    {{- include "digital-twin-bundle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "digital-twin-bundle.selectorLabels" . | nindent 4 }}
{{- end }} 