# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

# Default values for dataspace-connector-bundle
# This is a YAML-formatted file.

# Enable/disable the entire bundle
enabled: true
tractusx-connector:
  # Installation options
  install:
    # -- Deploying a PostgreSQL instance
    postgresql: false
    # -- Deploying a HashiCorp Vault instance
    vault: false

  # Participant Configuration
  participant:
    # -- Business Partner Number (BPN) for this participant
    id: "BPNL00000003AYRE"

  # IATP (Identity and Trust Protocol) Configuration
  iatp:
    # -- DID identifier for this participant
    id: "did:web:example.org:BPNL00000003AYRE"
    # -- List of trusted issuers' DIDs
    trustedIssuers:
      - "did:web:example.org:BPNL00000003CRHK"
    # -- Security Token Service configuration
    sts:
      dim:
        # -- DIM STS endpoint URL
        url: http://ssi-dim-wallet-stub.tx.test/api/sts
      oauth:
        token_url: http://ssi-dim-wallet-stub.tx.test/oauth/token
        client:
          id: BPNL00000003AZQP
          secret_alias: edc-wallet-secret

  # Control Plane Configuration
  controlplane:
    env:
      # -- Credential service URL
      TX_IAM_IATP_CREDENTIALSERVICE_URL: "http://example.org/api"
      # -- Disable HTTPS for DID Web (development only)
      EDC_IAM_DID_WEB_USE_HTTPS: false
    bdrs:
      server:
        # -- Business Directory Service URL
        url: "http://example.org/api/v1/directory"
    endpoints:
      management:
        # -- Authentication key for management API
        authKey: "changeme"
    ingresses:
      - enabled: true
        hostname: "controlplane.example.org"
        endpoints:
          - default
          - protocol
          - management
        className: "nginx"
        tls:
          enabled: false

  # Data Plane Configuration
  dataplane:
    env:
      # -- Credential service URL
      TX_IAM_IATP_CREDENTIALSERVICE_URL: "http://example.org/api"
      # -- Disable HTTPS for DID Web (development only)
      EDC_IAM_DID_WEB_USE_HTTPS: false
    ingresses:
      - enabled: true
        hostname: "dataplane.example.org"
        endpoints:
          - default
          - public
        className: "nginx"
        tls:
          enabled: false
    token:
      signer:
        privatekey_alias: "tokenSignerPrivateKey"
      verifier:
        publickey_alias: "tokenSignerPublicKey"



# PostgreSQL Configuration
postgresql:
  nameOverride: dataspace-connector-db
  enabled: true
  auth:
    username: "edc"
    password: "changeme"
    database: "edc"
  primary:
    persistence:
      enabled: true
      size: "10Gi"
  service:
    type: ClusterIP
    port: 5432

# Vault Configuration
vault:
  enabled: true
  server:
    standalone:
      enabled: true
    dev:
      enabled: false
  secretNames:
    transferProxyTokenSignerPrivateKey: "tokenSignerPrivateKey"
    transferProxyTokenSignerPublicKey: "tokenSignerPublicKey"
    transferProxyTokenEncryptionAesKey: "tokenEncryptionAesKey"