# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

# Default values for data-persistence-layer-bundle
# This is a YAML-formatted file.

# Enable/disable the entire bundle
enabled: true

# BPDM Gate Configuration
bpdm-gate:
  enabled: true
  postgres:
    fullnameOverride: "bpdm-postgres"
    nameOverride: "bpdm-postgres"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/gate"
    hosts:
      - host: "bpdm.example.org"
        paths:
          - path: "/gate(/|$)(.*)"
            pathType: "ImplementationSpecific"
  applicationConfig:
    server:
      forward-headers-strategy: "FRAMEWORK"
    bpdm:
      datasource:
        host: "bpdm-postgres"
      security:
        auth-server-url: "http://keycloak.example.org/auth"
        realm: "default"
        client-id: "bpdm-gate"
      client:
        pool:
          base-url: "http://bpdm.example.org/pool"
          registration:
            client-id: "bpdm-pool-client"
        orchestrator:
          base-url: "http://bpdm.example.org/orchestrator"
          registration:
            client-id: "bpdm-orchestrator-client"
  applicationSecrets:
    spring:
      datasource:
        password: "changeme"
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: "changeme"
        pool:
          registration:
            client-secret: "changeme"

# BPDM Pool Configuration
bpdm-pool:
  enabled: true
  postgres:
    fullnameOverride: "bpdm-postgres"
    nameOverride: "bpdm-postgres"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/pool"
    hosts:
      - host: "bpdm.example.org"
        paths:
          - path: "/pool(/|$)(.*)"
            pathType: "ImplementationSpecific"
  applicationConfig:
    server:
      forward-headers-strategy: "FRAMEWORK"
    bpdm:
      datasource:
        host: "bpdm-postgres"
      security:
        auth-server-url: "http://keycloak.example.org/auth"
        realm: "default"
        client-id: "bpdm-pool"
      client:
        orchestrator:
          base-url: "http://bpdm.example.org/orchestrator"
          registration:
            client-id: "bpdm-orchestrator-client"
  applicationSecrets:
    spring:
      datasource:
        password: "changeme"
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: "changeme"

# BPDM Orchestrator Configuration
bpdm-orchestrator:
  enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/orchestrator"
    hosts:
      - host: "bpdm.example.org"
        paths:
          - path: "/orchestrator(/|$)(.*)"
            pathType: "ImplementationSpecific"
  postgres:
    enabled: false
    fullnameOverride: "bpdm-postgres"
  applicationConfig:
    server:
      forward-headers-strategy: "FRAMEWORK"
    bpdm:
      datasource:
        host: "bpdm-postgres"
      security:
        auth-server-url: "http://keycloak.example.org/auth"
        realm: "default"
        client-id: "bpdm-orchestrator"
  applicationSecrets:
    spring:
      datasource:
        password: "changeme"

# BPDM Cleaning Service Configuration
bpdm-cleaning-service-dummy:
  enabled: true
  applicationConfig:
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm.example.org/orchestrator"
          provider:
            issuer-uri: "http://keycloak.example.org/auth/realms/default"
          registration:
            client-id: "bpdm-cleaning-service"
  applicationSecrets:
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: "changeme"

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: "bpdm"
    password: "changeme"
    database: "bpdm"
  primary:
    persistence:
      enabled: true
      size: "10Gi"
  service:
    type: ClusterIP
    port: 5432