# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

apiVersion: v2
name: identity-trust-bundle
description: |
  Identity & Trust Bundle Chart for Catena-X.
  This bundle includes:
  - Identity Wallet Mock
  - OAuth2 Authorization Server
  - Identity Provider Services

type: application
version: 1.0.0

dependencies:
  - name: identity-wallet-mock
    version: 1.0.0
    repository: https://eclipse-tractusx.github.io/charts/dev
    condition: identity-wallet-mock.enabled

  - name: oauth2-server
    version: 0.1.0
    repository: https://eclipse-tractusx.github.io/charts/dev
    condition: oauth2-server.enabled

  - name: ssi-credential-issuer
    version: 1.2.0
    repository: "file://./charts/ssi-credential-issuer"
    condition: ssiCredentialIssuer.enabled

  - name: sd-factory
    version: 2.1.22
    repository: "file://./charts/sd-factory"
    condition: sdFactory.enabled

  - name: bdrs-server-memory
    version: 0.5.2
    repository: "file://./charts/bdrs-server-memory"
    condition: bdrs.enabled

  - name: ssi-dim-wallet-stub
    version: 0.1.8
    repository: "file://./charts/ssi-dim-wallet-stub"
    condition: dimWalletStub.enabled