# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

# Default values for identity-and-trust-bundle
# This is a YAML-formatted file.

# Enable/disable the entire bundle
enabled: true

# SSI DIM Wallet Configuration
ssi-dim-wallet-stub:
  enabled: true
  wallet:
    replicaCount: 1
    host: "wallet.example.org"
    nameSpace: "identity-trust"
    appName: "ssi-dim-wallet"
    configName: "ssi-dim-wallet-config"
    serviceName: "ssi-dim-wallet-service"
    secretName: "ssi-dim-wallet-secret"
    ingressName: "ssi-dim-wallet-ingress"
    seeding:
      bpnList: "BPNL00000003AZQP,BPNL00000003AYRE"
    ingress:
      enabled: true
      tls:
        enabled: false
      urlPrefix: "/"
      className: "nginx"
      annotations: {}
    swagger:
      ui:
        status: true
      apiDoc:
        status: true
    logLevel: "debug"
    environment: "default"
    baseWalletBpn: "BPNL00000003CRHK"
    didHost: "wallet.example.org"
    stubUrl: "http://wallet.example.org"
    statusListVcId: "8a6c7486-1e1f-4555-bdd2-1a178182651e"
    tokenExpiryTime: "5"
    portal:
      waitTime: "60"
      host: "http://portal.example.org"
      clientId: "wallet-client"
      clientSecret: "changeme"
    keycloak:
      enabled: true
      realm: "default"
      authServerUrl: "http://keycloak.example.org/auth"
    service:
      type: ClusterIP
      port: 8080

# Keycloak Configuration
keycloak:
  enabled: true
  postgresql:
    enabled: true
    architecture: standalone
    primary:
      persistence:
        enabled: true
        size: "10Gi"
    auth:
      username: "keycloak"
      password: "changeme"
      database: "keycloak"
  auth:
    adminUser: "admin"
    adminPassword: "changeme"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    hostname: "keycloak.example.org"